# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: "home"
    url: "/"
    weight: 10

  - name: About
    identifier: "about"
    url: "#about"
    weight: 20

  - name: Calls
    identifier: "calls"
    weight: 30

  - name: Important Dates
    parent: "calls"
    url: "#calls"
    weight: 10

  - name: Call for Participation
    parent: "calls"
    url: "cfp/"
    weight: 20

#   - name: Call for Sponsorships
#     parent: "calls"
#     url: "cfs/"
#     weight: 30

  - name: Keynote speakers
    url: "keynotes/"
    weight: 10
    parent: "program"

  - name: Program
    identifier: "program"
    url: "program/"
    weight: 50

  - name: Schedule
    parent: "program"
    url: "schedule/"
    weight: 20

  - name: Proceedings
    parent: "program"
    url: "proceedings/"
    weight: 30

  - name: Posters
    parent: "program"
    url: "posters/"
    weight: 40

  - name: Video recordings
    parent: "program"
    url: "video-recordings/"
    weight: 50

  - name: Concert
    parent: "program"
    url: "concert/"
    weight: 60

  - name: Social Activities
    parent: "program"
    url: "social-activities"
    weight: 70

#   - name: Summer School (external)
#     parent: "program"
#     url: "https://www.actorproject.org/timbre-and-orchestration-summer-school"
#     weight: 30

#   - name: Social Activities
#     parent: "program"
#     url: "social/"
#     weight: 40

  - name: Attend
    identifier: "attend"
    url: "attend/"
    weight: 50


#   - name: Accommodation
#     parent: "attend"
#     url: accommodation
#     weight: 20

  - name: Location
    parent: "attend"
    url: "#host"
    weight: 10

  - name: Venue
    parent: "attend"
    url: "/venue"
    weight: 20

  - name: Travel
    parent: "attend"
    url: "/travel"
    weight: 30
  
  - name: Lodging
    parent: "attend"
    url: "/Lodging"
    weight: 40

  - name: Registration
    parent: "attend"
    url: registration
    weight: 5

  - name: Sponsors
    identifier: "sponsors"
    url: "#sponsors"
    weight: 70

  - name: Organizers
    identifier: "organizers"
    url: "organizers/"
    weight: 80
